import type { SourceDocumentSummary } from '@/features/modules/api/adminSourceDocumentsApi';
import type { ModuleDraftData } from '@/features/modules/types/moduleDraft.types';
import type { ModuleLibraryResponse } from '@/features/modules/types/moduleLibrary.types';

export const mockModuleLibrary: ModuleLibraryResponse = {
  modules: [
    {
      id: 'spice-visit',
      title: 'SPICE App — Visit Submission',
      category: 'SPICE App',
      lessons: 4,
      questions: 5,
      durationLabel: '~20 min',
      status: 'published',
      createdAt: '12 Apr 2026',
    },
    {
      id: 'htn-referral',
      title: 'HTN Referral Thresholds',
      category: 'Hypertension',
      lessons: 4,
      questions: 3,
      durationLabel: '~18 min',
      status: 'published',
      createdAt: '8 Apr 2026',
    },
    {
      id: 'community-clinic',
      title: 'Community Clinic Referral Protocol',
      category: 'Referral',
      lessons: 3,
      questions: 4,
      durationLabel: '~15 min',
      status: 'published',
      createdAt: '5 Apr 2026',
    },
    {
      id: 'fbs-rbs',
      title: 'FBS vs RBS — Timing Rules',
      category: 'Diabetes',
      lessons: 3,
      questions: 5,
      durationLabel: '~14 min',
      status: 'published',
      createdAt: '3 Apr 2026',
    },
    {
      id: 'med-adherence',
      title: 'Medication Adherence Counseling',
      category: 'SPICE App',
      lessons: 3,
      questions: 4,
      durationLabel: '~12 min',
      status: 'published',
      createdAt: '1 Apr 2026',
    },
    {
      id: 'danger-signs',
      title: 'Danger Signs in Pregnancy',
      category: 'Pregnancy',
      lessons: 5,
      questions: 6,
      durationLabel: '~22 min',
      status: 'published',
      createdAt: 'Overdue • 15 Apr',
    },
    {
      id: 'bp-technique',
      title: 'BP Measurement Technique',
      category: 'Hypertension',
      lessons: 2,
      questions: 0,
      durationLabel: '~10 min',
      status: 'draft',
      createdAt: '2 days ago',
      draftProgress: 'Step 2 of 4 — Lessons',
    },
    {
      id: 'insulin-guidance',
      title: 'Insulin Injection Guidance',
      category: 'Diabetes',
      lessons: 3,
      questions: 3,
      durationLabel: '~16 min',
      status: 'draft',
      createdAt: '5 days ago',
      draftProgress: 'Step 3 of 4 — Quiz',
    },
    {
      id: 'postnatal-checklist',
      title: 'Postnatal Care Checklist',
      category: 'Pregnancy',
      lessons: 1,
      questions: 0,
      durationLabel: '~5 min',
      status: 'draft',
      createdAt: '1 week ago',
      draftProgress: 'Step 2 of 4 — Lessons',
    },
  ],
};

export const mockCourseDraft: ModuleDraftData = {
  id: 'draft-htn-referral',
  title: '',
  topic: '',
  description: '',
  sourceFile: '',
  status: 'draft',
  generationStatus: 'idle',
  generatedAt: '',
  moduleDetails: {
    description: [],
    estimatedTime: 0,
  },
  lessons: [],
  moduleContent: {
    fieldMessage: '',
    objectives: [],
    dangerSigns: [],
    lessonContent: '',
  },
  quiz: {
    instructions: '',
    config: {
      shuffleQuestions: true,
      evaluationBehavior: 'immediate',
      explanationVisibility: 'after_answer',
    },
    questions: [],
  },
  estimateMinutes: 0,
};

export const mockSourceDocuments: SourceDocumentSummary[] = [
  {
    id: 'doc-htn-protocol',
    title: 'Hypertension Referral Protocol',
    source_type: 'pdf',
    status: 'ingested',
    content_domain: 'Hypertension',
    authority_label: 'MoH Bangladesh',
    original_filename: 'htn_referral_protocol.pdf',
    description: null,
    thumbnail_storage_path: null,
    ingested_at: '2026-04-08T09:00:00Z',
  },
  {
    id: 'doc-spice-visit-guide',
    title: 'SPICE App Visit Submission Guide',
    source_type: 'pdf',
    status: 'ingested',
    content_domain: 'SPICE App',
    authority_label: 'Program Team',
    original_filename: 'spice_visit_guide.pdf',
    description: null,
    thumbnail_storage_path: null,
    ingested_at: '2026-04-12T11:30:00Z',
  },
  {
    id: 'doc-referral-checklist',
    title: 'Community Clinic Referral Checklist',
    source_type: 'docx',
    status: 'ingested',
    content_domain: 'Referral',
    authority_label: 'Program Team',
    original_filename: 'referral_checklist.docx',
    description: null,
    thumbnail_storage_path: null,
    ingested_at: '2026-04-01T08:15:00Z',
  },
  {
    id: 'doc-htn-counselling-video',
    title: 'Hypertension Counselling Demonstration',
    source_type: 'video',
    status: 'ingested',
    content_domain: 'Hypertension',
    authority_label: 'Program Team',
    original_filename: 'htn_counselling_demo.mp4',
    description:
      'Demonstrationed counselling walkthrough for hypertension visits.',
    thumbnail_storage_path: 'thumbnails/htn_counselling_demo.jpg',
    ingested_at: '2026-04-15T10:00:00Z',
  },
];
