export const paths = {
  home: '/',
  chwProfiles: '/chw-profiles',
  chwProfileDetail: '/chw-profiles/:id',
  moduleLibrary: '/module-library',
  moduleAssigned: '/module-library/assigned',
  ingestDocument: '/module-library/ingest',
  adminModuleReview: '/module-library/review/:moduleId',
  adminModuleReviewDetails: '/module-library/review/:moduleId/details',
  adminModuleReviewLessons: '/module-library/review/:moduleId/lessons',
  adminModuleReviewQuiz: '/module-library/review/:moduleId/quiz',
  adminModuleReviewPublish: '/module-library/review/:moduleId/review',
  quizPerformance: '/quiz-performance',
  leaderboard: '/leaderboard',
  reports: '/reports',
  supervisors: '/supervisors',
  supervisorDetail: '/supervisors/:id',
  escalations: '/escalations',
  rankings: '/rankings',
  courseCreate: '/courses/new',
  courseLessons: '/courses/new/lessons',
  courseQuiz: '/courses/new/quiz',
  courseReview: '/courses/new/review',
  coursePublished: '/courses/new/published',
  /** Module creation flow (preferred). `course*` routes are kept for backwards compatibility. */
  moduleCreate: '/modules/new',
  moduleLessons: '/modules/new/lessons',
  moduleQuiz: '/modules/new/quiz',
  moduleReview: '/modules/new/review',
  modulePublished: '/modules/new/published',
  uiPreview: '/ui-preview',
  chartPreview: '/chart-preview',
} as const;
