export const paths = {
  home: '/',
  chwProfiles: '/chw-profiles',
  chwProfileDetail: '/chw-profiles/:id',
  moduleLibrary: '/module-library',
  moduleAssigned: '/module-library/assigned',
  quizPerformance: '/quiz-performance',
  leaderboard: '/leaderboard',
  reports: '/reports',
  supervisors: '/supervisors',
  supervisorDetail: '/supervisors/:id',
  escalations: '/escalations',
  rankings: '/rankings',
  courseCreate: '/courses/new',
  courseLessons: '/courses/new/lessons',
  courseQuiz: '/courses/new/quiz',
  courseReview: '/courses/new/review',
  coursePublished: '/courses/new/published',
  uiPreview: '/ui-preview',
  chartPreview: '/chart-preview',
} as const;
