server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;

    location = / {
        return 302 /medtronics-ui/;
    }

    location /medtronics-ui/ {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /medtronics-ui/index.html;
    }
}
